//! Deterministic artifact packaging and inspection.
//!
//! Build outputs are packed by trusted Loom code *outside* the sandbox, with
//! every source of non-determinism the Reproducible Builds project catalogues
//! for archives removed: sorted entries, fixed mtime (`SOURCE_DATE_EPOCH`),
//! uid/gid 0 with fixed names, normalised permissions, a gzip header with no
//! timestamp or filename, and a `.PKGINFO` generated from static metadata.
//! Symlinks are stored, never followed; device nodes, FIFOs and sockets are
//! refused.

use crate::srcinfo::SrcInfo;
use loom_core::ecosystem::{ArtifactFile, ArtifactManifest, FileKind};
use std::io::{Read, Write};
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};

fn walk(root: &Path, rel: &Path, out: &mut Vec<PathBuf>) -> anyhow::Result<()> {
    let mut entries: Vec<_> = std::fs::read_dir(root.join(rel))?
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|e| e.file_name());
    for e in entries {
        let r = rel.join(e.file_name());
        let meta = std::fs::symlink_metadata(root.join(&r))?;
        out.push(r.clone());
        if meta.is_dir() {
            walk(root, &r, out)?;
        }
    }
    Ok(())
}

pub fn normalise_mode(mode: u32, is_dir: bool) -> u32 {
    if is_dir {
        return 0o755;
    }
    let special = mode & 0o6000; // keep setuid/setgid so policy can see them
    let base = if mode & 0o111 != 0 { 0o755 } else { 0o644 };
    base | special
}

fn header(path: &str, mode: u32, mtime: u64) -> tar::Header {
    let mut h = tar::Header::new_gnu();
    h.set_path(path).expect("valid path");
    h.set_mode(mode);
    h.set_uid(0);
    h.set_gid(0);
    h.set_username("root").unwrap();
    h.set_groupname("root").unwrap();
    h.set_mtime(mtime);
    h
}

pub struct PackInput<'a> {
    pub pkgdir: &'a Path,
    pub info: &'a SrcInfo,
    pub install_script: Option<&'a [u8]>,
    pub source_date_epoch: i64,
    pub carch: &'a str,
}

pub fn pack(inp: &PackInput) -> anyhow::Result<Vec<u8>> {
    let mtime = inp.source_date_epoch.max(0) as u64;
    let mut paths = vec![];
    walk(inp.pkgdir, Path::new(""), &mut paths)?;

    let mut size: u64 = 0;
    for p in &paths {
        let m = std::fs::symlink_metadata(inp.pkgdir.join(p))?;
        if m.is_file() {
            size += m.len();
        }
    }
    let info = inp.info;
    let arch = if info.arch.iter().any(|a| a == "any") { "any" } else { inp.carch };
    let mut pkginfo = String::new();
    pkginfo.push_str("# Generated by Loom (deterministic)\n");
    pkginfo.push_str(&format!("pkgname = {}\n", info.pkgnames[0]));
    pkginfo.push_str(&format!("pkgbase = {}\n", info.pkgbase));
    pkginfo.push_str(&format!("pkgver = {}\n", info.full_version()));
    pkginfo.push_str(&format!("pkgdesc = {}\n", info.pkgdesc));
    pkginfo.push_str(&format!("url = {}\n", info.url));
    pkginfo.push_str(&format!("builddate = {mtime}\n"));
    pkginfo.push_str("packager = Loom Heddle <reproducible>\n");
    pkginfo.push_str(&format!("size = {size}\n"));
    pkginfo.push_str(&format!("arch = {arch}\n"));
    for l in &info.license {
        pkginfo.push_str(&format!("license = {l}\n"));
    }
    for d in &info.depends {
        pkginfo.push_str(&format!("depend = {d}\n"));
    }

    let gz = flate2::GzBuilder::new()
        .mtime(0)
        .operating_system(3)
        .write(Vec::new(), flate2::Compression::new(6));
    let mut tb = tar::Builder::new(gz);
    tb.mode(tar::HeaderMode::Deterministic);

    let add_bytes = |tb: &mut tar::Builder<_>, name: &str, data: &[u8]| -> anyhow::Result<()> {
        let mut h = header(name, 0o644, mtime);
        h.set_size(data.len() as u64);
        h.set_entry_type(tar::EntryType::Regular);
        h.set_cksum();
        tb.append(&h, data)?;
        Ok(())
    };
    add_bytes(&mut tb, ".PKGINFO", pkginfo.as_bytes())?;
    if let Some(s) = inp.install_script {
        add_bytes(&mut tb, ".INSTALL", s)?;
    }

    for p in &paths {
        let full = inp.pkgdir.join(p);
        let m = std::fs::symlink_metadata(&full)?;
        let name = p.to_string_lossy().to_string();
        let ft = m.file_type();
        if ft.is_dir() {
            let mut h = header(&format!("{name}/"), normalise_mode(m.mode(), true), mtime);
            h.set_entry_type(tar::EntryType::Directory);
            h.set_size(0);
            h.set_cksum();
            tb.append(&h, std::io::empty())?;
        } else if ft.is_symlink() {
            let target = std::fs::read_link(&full)?;
            let mut h = header(&name, 0o777, mtime);
            h.set_entry_type(tar::EntryType::Symlink);
            h.set_size(0);
            h.set_link_name(&target)?;
            h.set_cksum();
            tb.append(&h, std::io::empty())?;
        } else if ft.is_file() {
            let mut data = vec![];
            std::fs::File::open(&full)?.read_to_end(&mut data)?;
            let mut h = header(&name, normalise_mode(m.mode(), false), mtime);
            h.set_entry_type(tar::EntryType::Regular);
            h.set_size(data.len() as u64);
            h.set_cksum();
            tb.append(&h, data.as_slice())?;
        } else {
            anyhow::bail!("refusing to package special file {name} (device/fifo/socket)");
        }
    }
    let gz = tb.into_inner()?;
    let mut out = gz.finish()?;
    out.flush()?;
    Ok(out)
}

/// List an artifact's contents without extracting or executing anything.
pub fn inspect(artifact: &[u8]) -> anyhow::Result<ArtifactManifest> {
    let mut ar = tar::Archive::new(flate2::read::GzDecoder::new(artifact));
    let mut m = ArtifactManifest::default();
    for e in ar.entries()? {
        let mut e = e?;
        let path = e.path()?.to_string_lossy().trim_end_matches('/').to_string();
        if path.contains("..") {
            anyhow::bail!("artifact contains path traversal entry {path}");
        }
        match path.as_str() {
            ".PKGINFO" => {
                let mut s = String::new();
                e.read_to_string(&mut s)?;
                for l in s.lines() {
                    if let Some((k, v)) = l.split_once(" = ") {
                        match k {
                            "pkgname" => m.name = v.to_string(),
                            "pkgver" => m.version = v.to_string(),
                            _ => {}
                        }
                    }
                }
                continue;
            }
            ".INSTALL" => {
                let mut s = String::new();
                e.read_to_string(&mut s)?;
                m.install_script = Some(s);
                continue;
            }
            p if p.starts_with('.') && !p.contains('/') => continue,
            _ => {}
        }
        let h = e.header();
        let kind = match h.entry_type() {
            tar::EntryType::Directory => FileKind::Dir,
            tar::EntryType::Symlink => FileKind::Symlink,
            _ => FileKind::File,
        };
        m.files.push(ArtifactFile {
            path: format!("/{path}"),
            mode: h.mode()?,
            kind,
            size: h.size()?,
        });
    }
    Ok(m)
}

/// Remove `.INSTALL` from an artifact (so the system package manager never
/// runs install scriptlets unconfined; Loom runs them under Heddle per
/// policy). Deterministic: same input, same output.
pub fn strip_install(artifact: &[u8]) -> anyhow::Result<Vec<u8>> {
    let mut ar = tar::Archive::new(flate2::read::GzDecoder::new(artifact));
    let gz = flate2::GzBuilder::new()
        .mtime(0)
        .operating_system(3)
        .write(Vec::new(), flate2::Compression::new(6));
    let mut tb = tar::Builder::new(gz);
    for e in ar.entries()? {
        let mut e = e?;
        if e.path()?.to_string_lossy() == ".INSTALL" {
            continue;
        }
        let h = e.header().clone();
        let mut data = vec![];
        e.read_to_end(&mut data)?;
        tb.append(&h, data.as_slice())?;
    }
    Ok(tb.into_inner()?.finish()?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    fn info() -> SrcInfo {
        SrcInfo {
            pkgbase: "hello".into(),
            pkgnames: vec!["hello".into()],
            pkgver: "1.0".into(),
            pkgrel: "1".into(),
            ..Default::default()
        }
    }

    fn tree(dir: &Path, umask_like_mode: u32) {
        std::fs::create_dir_all(dir.join("usr/bin")).unwrap();
        std::fs::write(dir.join("usr/bin/hello"), b"#!/bin/sh\necho hi\n").unwrap();
        std::fs::set_permissions(dir.join("usr/bin/hello"), std::fs::Permissions::from_mode(umask_like_mode)).unwrap();
        std::fs::create_dir_all(dir.join("usr/share/doc/hello")).unwrap();
        std::fs::write(dir.join("usr/share/doc/hello/README"), b"readme").unwrap();
        std::os::unix::fs::symlink("hello", dir.join("usr/bin/hi")).unwrap();
    }

    #[test]
    fn deterministic_across_umask_and_mtime() {
        let a = tempfile::tempdir().unwrap();
        let b = tempfile::tempdir().unwrap();
        tree(a.path(), 0o755);
        std::thread::sleep(std::time::Duration::from_millis(1100));
        tree(b.path(), 0o775); // different umask
        let i = info();
        let pa = pack(&PackInput { pkgdir: a.path(), info: &i, install_script: None, source_date_epoch: 1700000000, carch: "x86_64" }).unwrap();
        let pb = pack(&PackInput { pkgdir: b.path(), info: &i, install_script: None, source_date_epoch: 1700000000, carch: "x86_64" }).unwrap();
        assert_eq!(loom_core::Digest::of(&pa), loom_core::Digest::of(&pb));

        let m = inspect(&pa).unwrap();
        assert_eq!(m.name, "hello");
        assert!(m.files.iter().any(|f| f.path == "/usr/bin/hello" && f.mode == 0o755));
        assert!(m.files.iter().any(|f| f.path == "/usr/bin/hi" && f.kind == FileKind::Symlink));
    }

    #[test]
    fn install_script_roundtrip_and_strip() {
        let a = tempfile::tempdir().unwrap();
        tree(a.path(), 0o755);
        let i = info();
        let p = pack(&PackInput { pkgdir: a.path(), info: &i, install_script: Some(b"post_install() { :; }"), source_date_epoch: 1, carch: "x86_64" }).unwrap();
        assert!(inspect(&p).unwrap().install_script.is_some());
        let s = strip_install(&p).unwrap();
        let m = inspect(&s).unwrap();
        assert!(m.install_script.is_none());
        assert_eq!(m.files.len(), inspect(&p).unwrap().files.len());
    }

    #[test]
    fn setuid_is_visible() {
        assert_eq!(normalise_mode(0o4755, false), 0o4755);
        assert_eq!(normalise_mode(0o600, false), 0o644);
        assert_eq!(normalise_mode(0o700, true), 0o755);
    }
}
