//! One-shot provisioning of a complete Loom deployment for the demo:
//! generates every key, writes every config file (client + services), and
//! initialises the mock AUR with the benign baseline versions.

use crate::mockaur::MockAur;
use loom_core::keys::SecretKey;
use std::path::{Path, PathBuf};

pub struct Endpoints {
    pub host: String,
    pub warp: u16,
    pub witnesses: Vec<u16>,
    pub threads: Vec<u16>,
    pub aur: u16,
    pub client_serve: u16,
}

impl Endpoints {
    pub fn default_on(host: &str) -> Self {
        Endpoints {
            host: host.to_string(),
            aur: 7700,
            warp: 7710,
            witnesses: vec![7721, 7722, 7723],
            threads: vec![7731, 7732, 7733],
            client_serve: 7781,
        }
    }
    fn url(&self, port: u16) -> String {
        format!("http://{}:{}", self.host, port)
    }
}

pub struct Rebuilder {
    pub id: String,
    pub org: String,
    pub image: String,
}

fn key_at(dir: &Path, name: &str) -> anyhow::Result<SecretKey> {
    let p = dir.join(format!("{name}.key"));
    SecretKey::load_or_generate(&p, name)
}

pub fn provision(home: &Path, fixtures: &Path, ep: &Endpoints, sandbox: Option<&str>) -> anyhow::Result<()> {
    let keys = home.join("keys");
    let etc = home.join("etc");
    let svc = home.join("svc");
    let state = home.join("aur");
    for d in [&keys, &etc, &svc, &state] {
        std::fs::create_dir_all(d)?;
    }

    let rebuilders = [
        Rebuilder { id: "thread-a".into(), org: "rebuild.example-a".into(), image: "archlinux:base-devel@snapshot-a".into() },
        Rebuilder { id: "thread-b".into(), org: "rebuild.example-b".into(), image: "archlinux:base-devel@snapshot-b".into() },
        Rebuilder { id: "thread-c".into(), org: "reproducible.example-c".into(), image: "cachyos:base-devel@snapshot-c".into() },
    ];

    // ---- keys
    let warp_key = key_at(&keys, "warp")?;
    let revoker_key = key_at(&keys, "revoker")?;
    let witness_keys: Vec<SecretKey> = (0..ep.witnesses.len())
        .map(|i| key_at(&keys, &format!("witness-{}", i + 1)))
        .collect::<Result<_, _>>()?;
    let thread_keys: Vec<SecretKey> = rebuilders
        .iter()
        .map(|r| key_at(&keys, &r.id))
        .collect::<Result<_, _>>()?;

    let origin = "demo.loom/warp";
    let log_vkey = loom_warp::notes::vkey(origin, &warp_key.public());

    // ---- mock AUR: publish benign baselines
    let aur = MockAur::open(&state, fixtures)?;
    aur.set_base_url(&ep.url(ep.aur));
    for (pkg, dir, maint) in [
        ("libweft", "1.0-1", "alice"),
        ("hello-loom", "1.2-1", "alice"),
        ("fastmover", "0.9-1", "dave"),
        ("tlsprobe", "2.0.1-1", "erin"),
        ("orphan-tool", "1.0-1", "bob"),
        ("npm-helper", "2.4-1", "carol"),
        ("forcepush-lib", "3.1-1", "frank"),
        ("divergent-bin", "1.0-1", "ivan"),
        ("pth-inject", "1.0-1", "heidi"),
    ] {
        aur.publish(pkg, dir, maint, false)?;
    }
    // Age the stable packages so they clear the 72h quarantine; leave
    // fastmover fresh.
    let old = loom_core::time::now() - 40 * 86400;
    for p in ["libweft", "hello-loom", "orphan-tool", "npm-helper", "forcepush-lib", "divergent-bin", "pth-inject"] {
        aur.set_published(p, old)?;
    }

    // ---- client config
    let witnesses_toml: String = ep
        .witnesses
        .iter()
        .zip(&witness_keys)
        .enumerate()
        .map(|(i, (port, k))| {
            format!(
                "[[witness]]\nname = \"witness-{}\"\nkey = \"{}\"\nurl = \"{}\"\n\n",
                i + 1,
                k.public().to_b64(),
                ep.url(*port)
            )
        })
        .collect();
    let rebuilders_toml: String = rebuilders
        .iter()
        .zip(&thread_keys)
        .zip(&ep.threads)
        .map(|((r, k), port)| {
            format!(
                "[[rebuilder]]\nid = \"{}\"\norg = \"{}\"\nkey = \"{}\"\nurl = \"{}\"\n\n",
                r.id,
                r.org,
                k.public().to_b64(),
                ep.url(*port)
            )
        })
        .collect();
    let sandbox_toml = match sandbox {
        Some(b) => format!("\n[sandbox]\nbackend = \"{b}\"\n"),
        None => String::new(),
    };
    let loom_toml = format!(
        r#"# Loom client configuration (demo). Generated by loom-testbed.
[aur]
rpc      = "{aur}/rpc/v5"
git      = "{aur_git}"
packages = "{aur}/packages.gz"

[log]
url    = "{warp}"
origin = "{origin}"
key    = "{log_vkey}"

{witnesses}{rebuilders}[[revoker]]
name = "loom-security"
key  = "{revoker}"

[peers]
urls   = [{peer_urls}]
listen = "{serve}"

[install]
backend = "root"
root    = "{target_root}"
{sandbox}"#,
        aur = ep.url(ep.aur),
        // The RPC returns file:// repo URLs, but the git template is also
        // provided for completeness; the RPC value wins.
        aur_git = aur.repo_url("{pkgbase}"),
        warp = ep.url(ep.warp),
        origin = origin,
        log_vkey = log_vkey,
        witnesses = witnesses_toml,
        rebuilders = rebuilders_toml,
        revoker = revoker_key.public().to_b64(),
        peer_urls = ep.threads.iter().map(|p| format!("\"{}\"", ep.url(*p))).collect::<Vec<_>>().join(", "),
        serve = format!("{}:{}", ep.host, ep.client_serve),
        target_root = home.join("target-root").display(),
        sandbox = sandbox_toml,
    );
    std::fs::write(etc.join("loom.toml"), loom_toml)?;
    std::fs::create_dir_all(home.join("target-root"))?;

    // Client policy: the SRS default, but reference the mock advisory feed.
    let policy = loom_weave::policy::DEFAULT_POLICY
        .replace("https://security.archlinux.org/all.json", &format!("{}/advisories.json", ep.url(ep.aur)));
    std::fs::write(etc.join("policy.toml"), policy)?;

    // ---- warp config
    let warp_key_path = keys.join("warp.key");
    let rebuilder_admit: String = rebuilders
        .iter()
        .zip(&thread_keys)
        .map(|(r, k)| format!("[[rebuilder]]\nid = \"{}\"\nkey = \"{}\"\n\n", r.id, k.public().to_b64()))
        .collect();
    let warp_toml = format!(
        "origin = \"{origin}\"\nkey = \"{key}\"\ndata = \"{data}\"\nlisten = \"{listen}\"\nwitnesses = [{witnesses}]\nsplit_view = false\n\n{rebuilders}[[revoker]]\nid = \"loom-security\"\nkey = \"{revoker}\"\n",
        origin = origin,
        key = warp_key_path.display(),
        data = home.join("warp-data").display(),
        listen = format!("{}:{}", ep.host, ep.warp),
        witnesses = ep.witnesses.iter().map(|p| format!("\"{}\"", ep.url(*p))).collect::<Vec<_>>().join(", "),
        rebuilders = rebuilder_admit,
        revoker = revoker_key.public().to_b64(),
    );
    std::fs::write(svc.join("warp.toml"), warp_toml)?;

    // ---- witness configs
    for (i, port) in ep.witnesses.iter().enumerate() {
        let w = format!(
            "name = \"witness-{}\"\nkey = \"{}\"\nstate = \"{}\"\nlisten = \"{}\"\nevil = false\n\n[[log]]\norigin = \"{origin}\"\nvkey = \"{vkey}\"\n",
            i + 1,
            keys.join(format!("witness-{}.key", i + 1)).display(),
            home.join(format!("witness-{}-state.json", i + 1)).display(),
            format!("{}:{}", ep.host, port),
            origin = origin,
            vkey = log_vkey,
        );
        std::fs::write(svc.join(format!("witness-{}.toml", i + 1)), w)?;
    }

    // ---- thread configs
    let min_tier = "reduced";
    let sandbox_line = sandbox.map(|b| format!("sandbox = \"{b}\"\n")).unwrap_or_default();
    for (i, r) in rebuilders.iter().enumerate() {
        let t = format!(
            "id = \"{id}\"\norg = \"{org}\"\nkey = \"{key}\"\nimage = \"{image}\"\nlog = \"{log}\"\ncache = \"{cache}\"\nlisten = \"{listen}\"\ntamper = false\nmin_tier = \"{tier}\"\n{sandbox}\n[aur]\nrpc = \"{aur}/rpc/v5\"\ngit = \"{git}\"\npackages = \"{aur}/packages.gz\"\n",
            id = r.id,
            org = r.org,
            key = keys.join(format!("{}.key", r.id)).display(),
            image = r.image,
            log = ep.url(ep.warp),
            cache = home.join(format!("thread-{}-cache", r.id)).display(),
            listen = format!("{}:{}", ep.host, ep.threads[i]),
            tier = min_tier,
            sandbox = sandbox_line,
            aur = ep.url(ep.aur),
            git = aur.repo_url("{pkgbase}"),
        );
        std::fs::write(svc.join(format!("{}.toml", r.id)), t)?;
    }

    // Persist the endpoint map for the demo script.
    let ports = serde_json::json!({
        "host": ep.host,
        "aur": ep.aur, "warp": ep.warp,
        "witnesses": ep.witnesses, "threads": ep.threads,
        "client_serve": ep.client_serve,
        "origin": origin,
        "log_vkey": log_vkey,
    });
    std::fs::write(home.join("endpoints.json"), serde_json::to_vec_pretty(&ports)?)?;
    Ok(())
}

pub fn home_from_env() -> PathBuf {
    std::env::var_os("LOOM_HOME").map(PathBuf::from).unwrap_or_else(|| PathBuf::from("/tmp/loom-demo"))
}
